baseURL = 'https://example.org/'
languageCode = 'fr-fr'
title = 'Patrimoine | Saint-Romans'
theme = 'ananke'
defaultContentLanguage = 'fr'
featured_image = 'assets/images/saint-romans.jpg'

[params]
custom_css = ["custom.scss"]
read_more_copy = "Lire"
date_format = "2 January 2006"
site_logo = "images/logo-saint-romans.png"
